/* ============================================================
 *  JParty build — runs on plain macOS with no Node:
 *     osascript -l JavaScript tools/build.js
 *  Reads dev.html (the Babel-in-the-browser page that stays the source of
 *  truth for load order), compiles every text/babel script with the React
 *  preset using Babel standalone under JavaScriptCore, and writes:
 *     dist/app.js   — all JSX files, compiled, in load order
 *     dist/data.js  — the plain-JS content packs, concatenated
 *     index.html    — dev.html with the Babel CDN removed and the 47 script
 *                     tags replaced by the two bundles (hash-stamped)
 *     sw.js         — SHELL list + VERSION regenerated from the same hash
 * ============================================================ */
ObjC.import('Foundation');
var ROOT = '/Users/jaydendinh/party-spinner/';
var BABEL = ROOT + 'tools/vendor/babel.min.js';
function read(p) { var s = $.NSString.stringWithContentsOfFileEncodingError(p, 4, null); if (!s || s.isNil()) throw new Error('cannot read ' + p); return s.js; }
function write(p, text) { $(text).writeToFileAtomicallyEncodingError(p, true, 4, null); }
function hash(str) { var h = 5381; for (var i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) | 0; return (h >>> 0).toString(36); }

var window = this, self = this, globalThis = this;
eval(read(BABEL));

var dev = read(ROOT + 'dev.html');
var tagRe = /<script([^>]*)\ssrc="([^"]+)"[^>]*><\/script>\s*\n?/g;
var babelSrcs = [], dataSrcs = [], firstLocalIndex = -1, m;
while ((m = tagRe.exec(dev))) {
  var attrs = m[1], src = m[2];
  if (/^https?:/.test(src)) continue;
  if (firstLocalIndex < 0) firstLocalIndex = m.index;
  var file = src.split('?')[0];
  if (/text\/babel/.test(attrs)) babelSrcs.push(file); else dataSrcs.push(file);
}

var app = '/* JParty — built ' + new Date().toISOString() + ' from dev.html. Do not edit: run tools/build.sh */\n"use strict";\n';
var t0 = Date.now(), lines = 0;
babelSrcs.forEach(function (f) {
  var src = read(ROOT + f);
  lines += src.split('\n').length;
  var out = Babel.transform(src, { presets: ['react'], compact: false, comments: false, sourceType: 'script', filename: f }).code;
  app += '\n/* ==== ' + f + ' ==== */\n' + out + '\n';
});
var compileMs = Date.now() - t0;
var data = '/* JParty content packs — built from dev.html. Do not edit: run tools/build.sh */\n';
dataSrcs.forEach(function (f) { data += '\n/* ==== ' + f + ' ==== */\n' + read(ROOT + f) + '\n'; });

/* every top-level const/function must stay a global: strict-mode concatenation
 * keeps them as script-scope bindings, which is exactly how the dev page behaves */
new Function(app);  // syntax check only — throws on a bad transform
new Function(data);

var stamp = hash(app + data + read(ROOT + 'css/app.css') + read(ROOT + 'css/tailwind.css'));
write(ROOT + 'dist/app.js', app);
write(ROOT + 'dist/data.js', data);

/* index.html: strip Babel CDN, swap the local tags for the two bundles */
var html = dev
  .replace(/<script src="https:\/\/unpkg\.com\/@babel\/standalone[^"]*"><\/script>\s*\n?/, '')
  /* the Tailwind Play CDN is a JIT compiler that ships ~400 KB of JS and builds the
   * stylesheet on every load; production uses the sheet generated by tools/tw.html */
  .replace(/<script src="https:\/\/cdn\.tailwindcss\.com"><\/script>\s*\n?/, '<link rel="stylesheet" href="css/tailwind.css?v=__STAMP__" />\n')
  .replace(/<!--[^>]*Babel[^>]*-->\s*\n?/g, '')
  .replace(/<!-- dev page[^>]*-->\s*\n?/g, '')
  .replace(/<!-- DEV PAGE[\s\S]*?-->\s*\n?/, '');
var localTags = [];
tagRe.lastIndex = 0;
while ((m = tagRe.exec(html))) if (!/^https?:/.test(m[2])) localTags.push(m[0]);
var bundleTags = '<script src="dist/data.js?v=' + stamp + '"></script>\n<script src="dist/app.js?v=' + stamp + '"></script>\n';
localTags.forEach(function (tag, i) { html = html.replace(tag, i === 0 ? bundleTags : ''); });
html = html
  .replace(/<!--[^>]*(quiz content packs|quiz engine|user-created content)[^>]*-->\s*\n?/g, '')
  .replace(/css\/app\.css\?v=[^"]+/, 'css/app.css?v=' + stamp)
  .replace(/__STAMP__/g, stamp)
  .replace('<title>JParty 🎉 (dev)</title>', '<title>JParty 🎉</title>\n<!-- Built by tools/build.sh from dev.html — do not edit by hand -->')
  /* production registers the service worker; the dev page deliberately does not */
  .replace('</body>', "<script>\n  if ('serviceWorker' in navigator && /^https?:$/.test(location.protocol)) {\n    window.addEventListener('load', function () { navigator.serviceWorker.register('./sw.js').catch(function () {}); });\n  }\n</script>\n</body>");
write(ROOT + 'index.html', html);

/* sw.js: SHELL + VERSION follow the bundle */
var sw = read(ROOT + 'sw.js');
sw = sw.replace(/const VERSION = '[^']+';/, "const VERSION = 'jparty-" + stamp + "';");
sw = sw.replace(/const SHELL = \[[\s\S]*?\];/, "const SHELL = [\n  './', './index.html', './manifest.webmanifest', './icon.svg', './css/app.css', './css/tailwind.css',\n  './dist/data.js', './dist/app.js',\n];");
sw = sw.replace(/\s*'https:\/\/unpkg\.com\/@babel\/standalone@7\/babel\.min\.js',/, '');
sw = sw.replace(/\s*'https:\/\/cdn\.tailwindcss\.com',/, '');
write(ROOT + 'sw.js', sw);

JSON.stringify({ jsxFiles: babelSrcs.length, dataFiles: dataSrcs.length, lines: lines, compileMs: compileMs, appKb: Math.round(app.length / 1024), dataKb: Math.round(data.length / 1024), stamp: stamp });
