/* Collect every token in the source that could be a Tailwind class, so tools/tw.html
 * can ask the Play CDN to generate CSS for all of them at once.
 *   osascript -l JavaScript tools/tw-extract.js  →  tools/tw-classes.js */
ObjC.import('Foundation');
var ROOT = '/Users/jaydendinh/party-spinner/';
var fm = $.NSFileManager.defaultManager;
function read(p) { var s = $.NSString.stringWithContentsOfFileEncodingError(p, 4, null); return (!s || s.isNil()) ? '' : s.js; }
function write(p, t) { $(t).writeToFileAtomicallyEncodingError(p, true, 4, null); }
function walk(dir) {
  var out = [], items = fm.contentsOfDirectoryAtPathError(dir, null);
  for (var i = 0; i < items.count; i++) {
    var name = ObjC.unwrap(items.objectAtIndex(i)), p = dir + '/' + name;
    var isDir = Ref(); fm.fileExistsAtPathIsDirectory(p, isDir);
    if (isDir[0]) out = out.concat(walk(p)); else if (/\.js$/.test(name)) out.push(p);
  }
  return out;
}
var files = walk(ROOT + 'js').filter(function (f) { return !/\/data\/quiz\//.test(f); }).concat([ROOT + 'dev.html']);
var tokens = {};
var tokenRe = /[A-Za-z0-9:\-\[\]\/\.%#(),_!]+/g;
function harvest(text) {
  var t;
  tokenRe.lastIndex = 0;
  while ((t = tokenRe.exec(text))) {
      var tok = t[0];
      if (!/[a-z]/.test(tok)) continue;
      if (/^(https?|data|image|application|url)/.test(tok)) continue;
      /* strip variant prefixes (hover:, lg:, dark:…) before judging the utility */
      var bare = tok.indexOf(':') >= 0 ? tok.slice(tok.lastIndexOf(':') + 1) : tok;
      if (!bare) continue;
      var BARE_OK = /^(flex|grid|hidden|block|inline|relative|absolute|fixed|sticky|truncate|italic|uppercase|lowercase|capitalize|underline|shrink|grow|invisible|visible|contents|isolate|border|rounded|shadow|ring|transition|transform|filter|blur|resize|container|static|table|contain|antialiased|appearance-none)$/;
      if (!/-|\//.test(bare) && !BARE_OK.test(bare)) continue;
    tokens[tok] = true;
  }
}
files.forEach(function (f) {
  var src = read(f);
  /* 1) everything inside string / template literals */
  var strRe = /(["'`])((?:\\.|(?!\1)[\s\S])*?)\1/g, m;
  while ((m = strRe.exec(src))) harvest(m[2]);
  /* 2) safety net: arbitrary-value utilities like text-[clamp(60px,14vmin,180px)]
   *    can be missed when quote pairing drifts, so scan the raw source for them too */
  var arb = src.match(/[a-z][a-z0-9-]*-\[[^\]\s]*\]/g) || [];
  arb.forEach(function (c) { tokens[c] = true; });
  var variantArb = src.match(/(?:[a-z]+:)+[a-z][a-z0-9-]*-\[[^\]\s]*\]/g) || [];
  variantArb.forEach(function (c) { tokens[c] = true; });
});
var list = Object.keys(tokens).sort();
write(ROOT + 'tools/tw-classes.js', '/* generated by tools/tw-extract.js — candidate Tailwind classes found in the source */\nwindow.TW_CLASSES = ' + JSON.stringify(list) + ';\n');
JSON.stringify({ files: files.length, candidates: list.length });
